version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "15:00"
      timezone: Asia/Tokyo
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    assignees:
      - "ara-ta3"
    ignore:
      - dependency-name: "node-fetch"
        versions: ["3.x"]
